// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2RNhaKYzCS3jFjoLBj-E9B17QKEabZAo',
    appId: '1:83316251266:web:749cb5e96d33bfdf9bf29b',
    messagingSenderId: '83316251266',
    projectId: 'edonate-e75ee',
    authDomain: 'edonate-e75ee.firebaseapp.com',
    storageBucket: 'edonate-e75ee.firebasestorage.app',
    measurementId: 'G-8EJBQ0R8SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn6_zR24t3-OgAe3ZPcSj-GDNf0hD9SyM',
    appId: '1:83316251266:android:bcf6d90adc0803a19bf29b',
    messagingSenderId: '83316251266',
    projectId: 'edonate-e75ee',
    storageBucket: 'edonate-e75ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgbSaGFLALFMkoVM73cQJTtiVayPyeVwU',
    appId: '1:83316251266:ios:a59b548263f3851f9bf29b',
    messagingSenderId: '83316251266',
    projectId: 'edonate-e75ee',
    storageBucket: 'edonate-e75ee.firebasestorage.app',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgbSaGFLALFMkoVM73cQJTtiVayPyeVwU',
    appId: '1:83316251266:ios:a59b548263f3851f9bf29b',
    messagingSenderId: '83316251266',
    projectId: 'edonate-e75ee',
    storageBucket: 'edonate-e75ee.firebasestorage.app',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2RNhaKYzCS3jFjoLBj-E9B17QKEabZAo',
    appId: '1:83316251266:web:134a4d92032e00579bf29b',
    messagingSenderId: '83316251266',
    projectId: 'edonate-e75ee',
    authDomain: 'edonate-e75ee.firebaseapp.com',
    storageBucket: 'edonate-e75ee.firebasestorage.app',
    measurementId: 'G-6XN3CFCCDM',
  );
}
